# Generated by Django 5.1.1 on 2024-10-30 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ovqat kategoriyasi nomi')),
                ('description', models.TextField(blank=True, verbose_name='ovqat kategoriyasi tavsifi')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Ovqat kategiriyasi',
                'verbose_name_plural': 'Ovqat kategiriyalari',
            },
        ),
        migrations.CreateModel(
            name='Chefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='oshpaz ismi')),
                ('slug', models.SlugField(max_length=100, verbose_name='oshpaz ismi')),
                ('description', models.TextField(blank=True, verbose_name='oshpaz haqida')),
                ('image', models.ImageField(upload_to='chefs/', verbose_name='oshpaz rasmi')),
                ('age', models.IntegerField(default=18, verbose_name='ochpazni yoshi')),
            ],
            options={
                'verbose_name': 'Oshpaz',
                'verbose_name_plural': 'Oshpazlar',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ovqat nomi')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(verbose_name='ovqat haqida')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ovqat narxi $')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='Chegirma (%)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.category')),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.chefs')),
            ],
            options={
                'verbose_name': 'Ovqat',
                'verbose_name_plural': 'Ovqatlar',
            },
        ),
    ]
