# Generated by Django 5.1.1 on 2024-10-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(default=1, upload_to='food/', verbose_name='ovqat rasmi'),
            preserve_default=False,
        ),
    ]
