# Generated by Django 5.1.1 on 2024-10-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefs',
            name='designation',
            field=models.CharField(blank=True, max_length=75, verbose_name='lavozmi'),
        ),
    ]
