# Generated by Django 5.1.1 on 2024-10-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_chefs_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Mijoz ismi')),
                ('booking_date', models.DateTimeField(verbose_name='Buyurtma sanasi')),
                ('people_count', models.IntegerField(default=1, verbose_name='Insonlar soni')),
                ('special_requests', models.TextField(blank=True, verbose_name='Maxsus talablar')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
    ]
