# Generated by Django 5.1.1 on 2024-11-03 04:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_testimonial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='restaurant.category'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=75, verbose_name='izoh matni')),
                ('full_name', models.CharField(max_length=100, verbose_name="To'liq ismi")),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, "kamida 1 ta bo'lishi kerak"), django.core.validators.MaxValueValidator(5, "eng ko'pi 5 ta bo'lishi kerak")], verbose_name='bahosi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name="izoh qo'shilgan vaqti")),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Izoh',
                'verbose_name_plural': 'Izohlar',
            },
        ),
    ]
