# Generated by Django 5.1.1 on 2024-11-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_food_category_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='profession',
            field=models.CharField(max_length=100, null=True, verbose_name='kasbi'),
        ),
    ]
